# create an account on http://pusher.com/
# and put your credentials bellow.
# Pusher.url = ENV["pusher_url"]
# Pusher.app_id = ENV["pusher_app_id"]
# Pusher.key = ENV["pusher_key"]
#
# Pusher.secret = ENV["pusher_secret"]
#

Pusher.url = ENV["pusher_url"]
Pusher.app_id = ENV["pusher_app_id"]
Pusher.key = ENV["pusher_key"]
Pusher.secret = ENV["pusher_secret"]


