# create an account on http://pusher.com/
# and put your credentials bellow.
# Pusher.url = ENV["pusher_url"]
app_id = '122739'
key = '429f0dfaaec2f4d689e8'
secret = '808cd9f52d25422d41ec'
#

# Pusher.url = Figaro.env.pusher_url
# Pusher.app_id = Figaro.env.pusher_app_id
# Pusher.key = Figaro.env.pusher_key
# Pusher.secret = Figaro.env.pusher_secret


