# create an account on http://pusher.com/
# and put your credentials bellow.
# Pusher.url = ENV["pusher_url"]
#app_id = '#####'
#key = '#######'
#secret = '######'
#


pusher_app_id = Figaro.env.pusher_app_id
pusher_key = Figaro.env.pusher_key
pusher_secret = Figaro.env.pusher_secret


