# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

main = ->
  $('#angkat_portal').click ->
    $.get '/angkat_portal'
    return
  $('#turunkan_portal').click ->
    $.get '/turunkan_portal'
    return
  pusher = new Pusher('#{Pusher.key}')
  channel = pusher.subscribe('button')
  channel.bind 'down', (data) ->
    $('body').css background: 'red'
    return
  channel.bind 'up', (data) ->
    $('body').css background: 'white'
    return
  return

$(document).ready main

# ---
# generated by js2coffee 2.0.4